<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Kernel\Turnify.Shared.Kernel\Turnify.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\Contracts\Turnify.Shared.Contracts\Turnify.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
